version: "3"
services:
  algorithm-nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - algorithm-php-fpm
    ports:
      - "8080:80"
  algorithm-php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app
  algorithm-php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
      - composer:/root/.composer/cache

volumes:
  composer: